// Renders per-file markdown and the index README from parsed + graph data.

import path from 'node:path'

function formatSignature(name, props) {
  if (!props.names.length) return `${name}()`
  const inner = props.names.join(', ')
  return props.destructured ? `${name}({ ${inner} })` : `${name}(${inner})`
}

function renderComponent(c) {
  const signature = formatSignature(c.name, c.props)
  const propsLine = c.props.names.length
    ? `Props: ${c.props.names.map(p => `\`${p}\``).join(', ')}`
    : 'No props.'
  return `### \`${signature}\`\n${propsLine}\n`
}

export function renderFileDoc({ rel, description, imports, components, dataConstants, sectionId, reachable, importedBy, root }) {
  let md = `# ${path.basename(rel)}\n\n`
  md += `\`${rel}\`\n\n`

  if (!reachable) {
    md += `> ⚠ **Not imported anywhere** — unreachable from \`src/main.jsx\`. Treat as dead code; edits here won't affect the live site.\n\n`
  }

  if (description) {
    md += `${description}\n\n`
  } else if (sectionId) {
    md += `_No description available. Renders a section with \`id="${sectionId}"\`._\n\n`
  }

  md += `## Imports\n`
  md += imports.length
    ? imports.map(i => `- \`${i.clause}\` from \`${i.source}\``).join('\n') + '\n\n'
    : '_None_\n\n'

  if (importedBy.length) {
    md += `## Imported by\n`
    md += importedBy.map(f => `- \`${path.relative(root, f)}\``).join('\n') + '\n\n'
  }

  const exportedComponents = components.filter(c => c.exported)
  const helperComponents = components.filter(c => !c.exported)

  md += `## Exports\n`
  md += exportedComponents.length
    ? exportedComponents.map(renderComponent).join('\n') + '\n'
    : '_None found._\n\n'

  if (helperComponents.length) {
    md += `## Internal helpers\n`
    md += helperComponents.map(renderComponent).join('\n') + '\n'
  }

  if (dataConstants.length) {
    md += `## Local data constants\n`
    md += dataConstants.map(c => `- \`${c}\``).join('\n') + '\n\n'
  }

  return md
}

export function renderIndex(entries) {
  let index = `# Source Documentation\n\n`
  index += `Auto-generated by \`npm run docs\` (\`scripts/generate-docs.js\`). Do not edit by hand — re-run the script to refresh.\n\n`
  index += `| File | Exports | Orphan | Description |\n|---|---|---|---|\n`
  for (const entry of entries) {
    const exportedNames = entry.components.filter(c => c.exported).map(c => c.name).join(', ') || '—'
    const desc = entry.description || '—'
    const orphan = entry.reachable ? '' : '⚠'
    index += `| [${entry.rel}](./${entry.rel}.md) | ${exportedNames} | ${orphan} | ${desc} |\n`
  }
  return index
}
